apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "hetzner-routes.fullname" . }}
  labels:
    app: {{ template "hetzner-routes.name" . }}
    chart: {{ template "hetzner-routes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "hetzner-routes.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hetzner-routes.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          SecurityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
